/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.*;

/**
 *
 * @author laboratorio_computo
 */
public class FrmEjercicio01 extends javax.swing.JFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();

    public FrmEjercicio01() {
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);

        this.setLocationRelativeTo(null);

        this.rbTiempoCompleto.setSelected(true);

        this.cargarComboEspecialidad();
        configurarCabeceraTabla();

        txtMaestria.setEnabled(false);
        
        habilitardesabilitar(false);
    }

    private void cargarComboEspecialidad() {
        cboEspecialidad.removeAllItems();
        cboEspecialidad.addItem("");
        cboEspecialidad.addItem("Administracion");
        cboEspecialidad.addItem("Contabilidad");
        cboEspecialidad.addItem("Economía");
        cboEspecialidad.addItem("Industrial");
        cboEspecialidad.addItem("Sistemas");
    }

    private void configurarCabeceraTabla() {
        modeloTabla.addColumn("Dni");
        modeloTabla.addColumn("Apellidos y Nombres");
        modeloTabla.addColumn("Sueldo");
        modeloTabla.addColumn("Especialidad");
        modeloTabla.addColumn("Dedicación");
        modeloTabla.addColumn("Maestria");
        modeloTabla.addColumn("Nombre Maestria");

        tblListado.setModel(modeloTabla);

        tblListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        tblListado.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblListado.getColumnModel().getColumn(1).setPreferredWidth(250);
        tblListado.getColumnModel().getColumn(2).setPreferredWidth(70);
        tblListado.getColumnModel().getColumn(3).setPreferredWidth(180);
        tblListado.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblListado.getColumnModel().getColumn(5).setPreferredWidth(120);
        tblListado.getColumnModel().getColumn(6).setPreferredWidth(300);
    }
    
    /*
    private void habilitar(){
        txtDni.setEnabled(true);
        txtMaestria.setEnabled(true);
        txtNombreyApellidos.setEnabled(true);
        txtSueldo.setEnabled(true);
        cboEspecialidad.setEnabled(true);
        rbMedioTiempo.setEnabled(true);
        rbTiempoCompleto.setEnabled(true);
        chkMaestria.setEnabled(true);
        
        btnNuevo.setEnabled(false);
        btnRegistrar.setEnabled(true);
    }
    
    private void deshabilitar(){
        txtDni.setEnabled(false);
        txtMaestria.setEnabled(false);
        txtNombreyApellidos.setEnabled(false);
        txtSueldo.setEnabled(false);
        cboEspecialidad.setEnabled(false);
        rbMedioTiempo.setEnabled(false);
        rbTiempoCompleto.setEnabled(false);
        chkMaestria.setEnabled(false);
        
        btnNuevo.setEnabled(true);
        btnRegistrar.setEnabled(false);
    }
    */
    
    
    private void habilitardesabilitar(boolean tf){
        txtDni.setEnabled(tf);
        txtNombreyApellidos.setEnabled(tf);
        txtSueldo.setEnabled(tf);
        cboEspecialidad.setEnabled(tf);
        rbMedioTiempo.setEnabled(tf);
        rbTiempoCompleto.setEnabled(tf);
        chkMaestria.setEnabled(tf);
        
        if (tf==true) {
            btnNuevo.setEnabled(false);
            btnRegistrar.setEnabled(true);
        }else if (tf==false) {
            btnNuevo.setEnabled(true);
            btnRegistrar.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboEspecialidad = new javax.swing.JComboBox();
        rbTiempoCompleto = new javax.swing.JRadioButton();
        rbMedioTiempo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        chkMaestria = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtMaestria = new javax.swing.JTextField();
        txtNombreyApellidos = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Colaboradores");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colaboradores.png"))); // NOI18N
        jLabel1.setText("Registro de Colaboradores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Dni");

        txtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniFocusLost(evt);
            }
        });
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombres y Apellidos");

        jLabel4.setText("Sueldo");

        jLabel5.setText("Especialidad");

        cboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rbTiempoCompleto);
        rbTiempoCompleto.setText("Tiempo Completo");

        buttonGroup1.add(rbMedioTiempo);
        rbMedioTiempo.setText("Medio Tiempo");

        jLabel6.setText("Dedicaciòn");

        chkMaestria.setText("Tiene maestrìa en la especialidad");
        chkMaestria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaestriaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre de la Maestrìa");

        txtMaestria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaestriaFocusLost(evt);
            }
        });

        txtNombreyApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreyApellidosFocusLost(evt);
            }
        });
        txtNombreyApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreyApellidosKeyTyped(evt);
            }
        });

        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1452717139_floppy.png"))); // NOI18N
        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1452555457_sign-error.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListado);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1452555529_exit-to-app.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1452716984_Add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbMedioTiempo)
                                    .addComponent(rbTiempoCompleto)
                                    .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkMaestria)
                                    .addComponent(txtNombreyApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(txtMaestria)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreyApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbTiempoCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbMedioTiempo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(chkMaestria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        if (txtDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dni Vacio...", "Verifique", JOptionPane.WARNING_MESSAGE);
            txtDni.requestFocus();
            return;
        } else if (txtNombreyApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombres y Apellidos Vacio...", "Verifique", JOptionPane.WARNING_MESSAGE);
            txtNombreyApellidos.requestFocus();
            return;
        } else if (txtSueldo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sueldo Vacio...", "Verifique", JOptionPane.ERROR_MESSAGE);
            txtSueldo.requestFocus();
            return;
        } else if (cboEspecialidad.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una especialidad...", "Verifique", JOptionPane.INFORMATION_MESSAGE);
            txtNombreyApellidos.requestFocus();
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estas seguro de guardar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if (confirmacion == 0) {

            String dni, nombresapellidos, especialidad, dedicacion = "", tieneMaestria = "", nombreMaestria = "";
            double sueldo;

            dni = txtDni.getText();
            nombresapellidos = txtNombreyApellidos.getText();
            sueldo = Double.parseDouble(txtSueldo.getText());
            especialidad = cboEspecialidad.getSelectedItem().toString();

            if (rbTiempoCompleto.isSelected()) {
                dedicacion = "TC";
            } else {
                dedicacion = "MT";
            }

            if (chkMaestria.isSelected()) {
                tieneMaestria = "SI";
                nombreMaestria = txtMaestria.getText();
                if (nombreMaestria.equals("")) {
                    JOptionPane.showMessageDialog(this, "Nombre de la maestria Vacía", "Verifique", JOptionPane.INFORMATION_MESSAGE);
                    txtMaestria.requestFocus();
                    return;
                }
            } else {
                tieneMaestria = "NO";
            }

            Object datos[] = new Object[7];
            datos[0] = dni;
            datos[1] = nombresapellidos;
            datos[2] = sueldo;
            datos[3] = especialidad;
            datos[4] = dedicacion;
            datos[5] = tieneMaestria;
            datos[6] = nombreMaestria;

            modeloTabla.addRow(datos);

            tblListado.setModel(modeloTabla);

            txtDni.setText("");
            txtNombreyApellidos.setText("");
            txtSueldo.setText("");
            txtMaestria.setText("");
            rbTiempoCompleto.setSelected(true);
            chkMaestria.setSelected(false);
            cboEspecialidad.setSelectedIndex(0);
            txtDni.requestFocus();
            
            habilitardesabilitar(false);
        } else {
            return;
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void chkMaestriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaestriaActionPerformed
        if (chkMaestria.isSelected()) {
            txtMaestria.setEnabled(true);
            txtMaestria.requestFocus();
        } else {
            txtMaestria.setEnabled(false);
            txtMaestria.setText("");
        }
    }//GEN-LAST:event_chkMaestriaActionPerformed

    private void txtDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniFocusLost
        if (txtDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dni Vacio...", "Verifique", JOptionPane.WARNING_MESSAGE);
            txtDni.requestFocus();
            return;
        } else if (txtDni.getText().length() != 8) {
            JOptionPane.showMessageDialog(this, "El dni debe tener 8 numeros", "Verifique", JOptionPane.WARNING_MESSAGE);
            txtDni.requestFocus();
            return;
        }
    }//GEN-LAST:event_txtDniFocusLost

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        Funciones.soloNumeros(evt, txtDni, 8);
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
        Funciones.soloNumerosDecimal(evt, txtSueldo, 10);
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void txtNombreyApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreyApellidosKeyTyped
        Funciones.soloLetras(evt, txtNombreyApellidos, 50);
    }//GEN-LAST:event_txtNombreyApellidosKeyTyped

    private void txtNombreyApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreyApellidosFocusLost
        if (txtNombreyApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombres y Apellidos Vacio...", "Verifique", JOptionPane.WARNING_MESSAGE);
            txtNombreyApellidos.requestFocus();
            return;
        }
    }//GEN-LAST:event_txtNombreyApellidosFocusLost

    private void txtMaestriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaestriaFocusLost

    }//GEN-LAST:event_txtMaestriaFocusLost

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblListado.getSelectedRow();
        if (fila < 0) {
            Funciones.mensajeError("Debe seleccionar una fila", "Verifique");
            return;
        } 
        
        int confirmacion = Funciones.mensajeConfirmacion("Desea Eliminar...", "Confirme");
        
        if (confirmacion==0) {
            modeloTabla.removeRow(fila);        
            tblListado.setModel(modeloTabla);
        }
        

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
           habilitardesabilitar(true);
           this.txtDni.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboEspecialidad;
    private javax.swing.JCheckBox chkMaestria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbMedioTiempo;
    private javax.swing.JRadioButton rbTiempoCompleto;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMaestria;
    private javax.swing.JTextField txtNombreyApellidos;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
